/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

/**
 *
 * @author aluno
 */
public class ifcJcheckBox extends javax.swing.JCheckBox {
    
    
    
    private String textoSelecionado = "S";
    private String textoNaoSelecionado = "N";
    private Object objeto;
    

    /**
     * Creates new form ifcJcheckBox
     */
    public ifcJcheckBox() {
        initComponents();
    }
    
    public ifcJcheckBox(String texto, Boolean selecionado) {
    this();
    this.setText(texto);
    this.setSelected(selecionado);
  }

  public String getValorSelecionado() {
    if (this.isSelected()) {
      return this.textoSelecionado;
    } else {
      return this.textoNaoSelecionado;
    }
  }

  public Object getObjetoSelecionado() {
    return isSelected() ? objeto : null;
  }

  public String getTextoSelecionado() {
    return textoSelecionado;
  }

  public void setTextoSelecionado(String textoSelecionado) {
    this.textoSelecionado = textoSelecionado;
  }

  public String getTextoNaoSelecionado() {
    return textoNaoSelecionado;
  }

  public void setTextoNaoSelecionado(String textoNaoSelecionado) {
    this.textoNaoSelecionado = textoNaoSelecionado;
  }

  public Object getObjeto() {
    return objeto;
  }

  public void setObjeto(Object objeto) {
    this.objeto = objeto;
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
